import type {UserData} from "./user-card.tsx";

export const mockUsers: UserData[] = [
    {
        id: 1,
        firstName: "Olena",
        lastName: "Ivanenko",
        gender: "female",
        age: 12,
        position: "UI/UX Designer",
        photo: "https://randomuser.me/api/portraits/women/1.jpg",
        email: "olena.ivanenko@example.com",
        hobbies: ["Drawing", "Photography", "Yoga"],
    },
    {
        id: 2,
        firstName: "Dmytro",
        lastName: "Shevchenko",
        gender: "male",
        age: 32,
        position: "Backend Developer",
        photo: "https://randomuser.me/api/portraits/men/2.jpg",
        email: "dmytro.shevchenko@example.com",
        hobbies: ["Cycling", "Chess", "Cooking"],
    },
    {
        id: 3,
        firstName: "Iryna",
        lastName: "Bondarenko",
        gender: "female",
        age: 24,
        position: "QA Engineer",
        photo: "https://randomuser.me/api/portraits/women/3.jpg",
        email: "iryna.bondarenko@example.com",
        hobbies: ["Reading", "Running", "Board games"],
    },
    {
        id: 4,
        firstName: "Oleksandr",
        lastName: "Koval",
        gender: "male",
        age: 29,
        position: "Frontend Developer",
        photo: "https://randomuser.me/api/portraits/men/4.jpg",
        email: "oleksandr.koval@example.com",
        hobbies: ["Gaming", "Football", "Traveling"],
    },
    {
        id: 5,
        firstName: "Kateryna",
        lastName: "Melnyk",
        gender: "female",
        age: 27,
        position: "Project Manager",
        photo: "https://randomuser.me/api/portraits/women/5.jpg",
        email: "kateryna.melnyk@example.com",
        hobbies: ["Dancing", "Cooking", "Swimming"],
    },
    {
        id: 6,
        firstName: "Andriy",
        lastName: "Tkachenko",
        gender: "male",
        age: 35,
        position: "DevOps Engineer",
        photo: "https://randomuser.me/api/portraits/men/6.jpg",
        email: "andriy.tkachenko@example.com",
        hobbies: ["Hiking", "Fishing", "Electronics"],
    },
    {
        id: 7,
        firstName: "Natalia",
        lastName: "Hrytsenko",
        gender: "female",
        age: 31,
        position: "Business Analyst",
        photo: "https://randomuser.me/api/portraits/women/7.jpg",
        email: "natalia.hrytsenko@example.com",
        hobbies: ["Puzzles", "Traveling", "Cooking"],
    },
    {
        id: 8,
        firstName: "Serhii",
        lastName: "Polishchuk",
        gender: "male",
        age: 26,
        position: "Data Scientist",
        photo: "https://randomuser.me/api/portraits/men/8.jpg",
        email: "serhii.polishchuk@example.com",
        hobbies: ["AI", "Running", "Books"],
    },
    {
        id: 9,
        firstName: "Anastasiia",
        lastName: "Moroz",
        gender: "female",
        age: 23,
        position: "Marketing Specialist",
        photo: "https://randomuser.me/api/portraits/women/9.jpg",
        email: "anastasiia.moroz@example.com",
        hobbies: ["Instagram", "Makeup", "Blogging"],
    },
    {
        id: 10,
        firstName: "Volodymyr",
        lastName: "Chernenko",
        gender: "male",
        age: 40,
        position: "CTO",
        photo: "https://randomuser.me/api/portraits/men/10.jpg",
        email: "volodymyr.chernenko@example.com",
        hobbies: ["Golf", "Reading", "Tech news"],
    },
    {
        id: 11,
        firstName: "Tetiana",
        lastName: "Petrenko",
        gender: "female",
        age: 30,
        position: "HR Manager",
        photo: "https://randomuser.me/api/portraits/women/11.jpg",
        email: "tetiana.petrenko@example.com",
        hobbies: ["Cooking", "Gardening", "Yoga"],
    },
    {
        id: 12,
        firstName: "Maksym",
        lastName: "Horobets",
        gender: "male",
        age: 22,
        position: "Intern Developer",
        photo: "https://randomuser.me/api/portraits/men/12.jpg",
        email: "maksym.horobets@example.com",
        hobbies: ["Gaming", "Music", "Skateboarding"],
    },
    {
        id: 13,
        firstName: "Yuliia",
        lastName: "Kravchenko",
        gender: "female",
        age: 34,
        position: "Product Owner",
        photo: "https://randomuser.me/api/portraits/women/13.jpg",
        email: "yuliia.kravchenko@example.com",
        hobbies: ["Cooking", "Reading", "Meditation"],
    },
    {
        id: 14,
        firstName: "Roman",
        lastName: "Lysenko",
        gender: "male",
        age: 28,
        position: "System Administrator",
        photo: "https://randomuser.me/api/portraits/men/14.jpg",
        email: "roman.lysenko@example.com",
        hobbies: ["Cars", "Gaming", "Hiking"],
    },
    {
        id: 15,
        firstName: "Svitlana",
        lastName: "Vasylenko",
        gender: "female",
        age: 25,
        position: "Content Manager",
        photo: "https://randomuser.me/api/portraits/women/15.jpg",
        email: "svitlana.vasylenko@example.com",
        hobbies: ["Writing", "Reading", "Traveling"],
    },
    {
        id: 16,
        firstName: "Bohdan",
        lastName: "Kuzmenko",
        gender: "male",
        age: 36,
        position: "Team Lead",
        photo: "https://randomuser.me/api/portraits/men/16.jpg",
        email: "bohdan.kuzmenko@example.com",
        hobbies: ["Fishing", "Basketball", "Tech"],
    },
    {
        id: 17,
        firstName: "Oksana",
        lastName: "Rudenko",
        gender: "female",
        age: 27,
        position: "Graphic Designer",
        photo: "https://randomuser.me/api/portraits/women/17.jpg",
        email: "oksana.rudenko@example.com",
        hobbies: ["Drawing", "Fashion", "Cycling"],
    },
    {
        id: 18,
        firstName: "Yevhen",
        lastName: "Marchenko",
        gender: "male",
        age: 33,
        position: "Fullstack Developer",
        photo: "https://randomuser.me/api/portraits/men/18.jpg",
        email: "yevhen.marchenko@example.com",
        hobbies: ["Coding", "Music", "Football"],
    },
    {
        id: 19,
        firstName: "Halyna",
        lastName: "Klymenko",
        gender: "female",
        age: 29,
        position: "PR Manager",
        photo: "https://randomuser.me/api/portraits/women/19.jpg",
        email: "halyna.klymenko@example.com",
        hobbies: ["Networking", "Blogging", "Dancing"],
    },
    {
        id: 20,
        firstName: "Petro",
        lastName: "Savchenko",
        gender: "male",
        age: 41,
        position: "CEO",
        photo: "https://randomuser.me/api/portraits/men/20.jpg",
        email: "petro.savchenko@example.com",
        hobbies: ["Business", "Traveling", "Golf"],
    },
];
